route:
  group_by: ['alertname','instance','alert']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'alertmananger-bot'

receivers:
- name: 'alertmananger-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://10.69.0.200:18080'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
