version: '3.3'
services:
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
    - ./alertmanager:/etc/alertmanager
  alertmanager-bot:
    container_name: alertmanager-bot
    image: metalmatze/alertmanager-bot:latest
    restart: unless-stopped
    environment:
      ALERTMANAGER_URL: http://10.69.0.200:9093
      BOLT_PATH: /tmp/bot.db
      LISTEN_ADDR: 0.0.0.0:8080
      STORE: bolt
      TELEGRAM_ADMIN: $TELEGRAM_ADMIN
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
      TEMPLATE_PATHS: /templates/default.tmpl
      http_proxy: http://10.69.0.50:3128
      https_proxy: http://10.69.0.50:3128
    ports:
      - "18080:8080"
    volumes:
    - ./alertmanager-bot/templates/default.tmpl:/templates/default.tmpl
  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    restart: unless-stopped
    volumes:
    - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
  grafana:
    container_name: grafana2
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    image: grafana/grafana:latest
    ports:
      - "13000:3000"
    restart: unless-stopped
    user: root
    volumes:
    - ./grafana:/var/lib/grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://10.69.0.200:19090
    ports:
      - "19090:9090"
    volumes:
    - ./prometheus:/etc/prometheus
  snmp_exporter:
    container_name: snmp_exporter
    image: prom/snmp-exporter:latest
    ports:
      - "9116:9116"
    restart: unless-stopped
