global:
  scrape_interval: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.122.90:9093

rule_files:
  - alerts/blackbox.yml
  - alerts/docker.yml
  - alerts/etcd.yml
  - alerts/haproxy.yml
  - alerts/host.yml
  - alerts/java.yml
  - alerts/nginx.yml 
  - alerts/postgresql.yml
  - alerts/prometheus.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - 192.168.122.90:9090
      labels:
        instance: prometheus

  - job_name: blackbox
    static_configs:
    - targets: 
      - 192.168.122.90:9115
      labels:
        instance: blackbox
 
  - job_name: haproxy
    file_sd_configs:
      - files:
        - haproxy.json
    
  - job_name: node
    file_sd_configs:
      - files:
        - node.json

  - job_name: cadvisor
    file_sd_configs:
      - files:
        - cadvisor.json

  - job_name: etcd
    file_sd_configs:
      - files:
        - etcd.json

  - job_name: java
    file_sd_configs:
      - files:
        - java.json

  - job_name: postgres
    file_sd_configs:
      - files:
        - postgres.json

  - job_name: http_2xx
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - http_2xx.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.122.90:9115

  - job_name: icmp
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - icmp.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.122.90:9115

  - job_name: snmp
    metrics_path: /snmp
    params:
      module: [if_mib]
    file_sd_configs:
      - files:
        - snmp.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.122.90:9116
