version: '3.7'
services:
  alertmanager:
    container_name: karma
    image: lmierzwa/karma:latest
    restart: unless-stopped
    environment:
      ALERTMANAGER_URI: http://192.168.122.90:9093
    ports:
      - "9632:8080"
