groups:
- name: node-exporter
  rules:
  - record: instance:node_num_cpu:sum
    expr: count without (cpu) (count without (mode) (node_cpu_seconds_total))
  - record: instance:node_cpu_utilisation:rate1m
    expr: 1 - avg without (cpu, mode) (rate(node_cpu_seconds_total{mode="idle"}[1m]))
  - record: instance:node_load1_per_cpu:ratio
    expr: (node_load1/instance:node_num_cpu:sum)
  - record: instance:node_memory_utilisation:ratio
    expr: 1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)
  - record: instance:node_memory_swap_io_pages:rate1m
    expr: (rate(node_vmstat_pgpgin[1m])+rate(node_vmstat_pgpgout[1m]))
  - record: instance_device:node_disk_io_time_seconds:rate1m
    expr: rate(node_disk_io_time_seconds_total[1m])
  - record: instance_device:node_disk_io_time_weighted_seconds:rate1m
    expr: rate(node_disk_io_time_weighted_seconds_total[1m])
  - record: instance:node_network_receive_bytes_excluding_lo:rate1m
    expr: sum without (device) (rate(node_network_receive_bytes_total{device!="lo"}[1m]))
  - record: instance:node_network_transmit_bytes_excluding_lo:rate1m
    expr: sum without (device) (rate(node_network_transmit_bytes_total{device!="lo"}[1m]))
  - record: instance:node_network_receive_drop_excluding_lo:rate1m
    expr: sum without (device) (rate(node_network_receive_drop_total{device!="lo"}[1m]))
  - record: instance:node_network_transmit_drop_excluding_lo:rate1m
    expr: sum without (device) (rate(node_network_transmit_drop_total{device!="lo"}[1m]))
