version: '3.3'
services:
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "18081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
