groups:
- name: HAProxy
  rules:
    - alert: HAProxyInstanceDown
      expr: up{job="haproxy"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy down (instance {{ $labels.instance }})"
        description: "HAProxy are unhealthy\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: HAProxyMissing
      expr: absent(up{job="haproxy"})
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy is missing (instance {{ $labels.instance }})"
        description: "HAProxy server are unhealthy\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
