groups:
- name: HAProxy
  rules:
    - alert: HAProxyDown
      expr: haproxy_backend_active_servers{proxy="haproxy_pool"} < 2
      labels:
        severity: warning
      annotations:
        summary: "HAProxy server are unhealthy  (instance {{ $labels.instance }})"
        description: "HAProxy server are unhealthy\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
