groups:
- name: PostgreSQL
  rules:
    - alert: PostgresqlDown
      expr: pg_up == 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "PostgreSQL down (instance {{ $labels.instance }})"
        description: "PostgreSQL instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: ReplicationLag
      expr: pg_replication_lag > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Replication lag (instance {{ $labels.instance }})"
        description: "PostgreSQL replication lag is going up (> 10s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: TableNotVaccumed
      expr: time() - pg_stat_user_tables_last_autovacuum > 60 * 60 * 24
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Table not vaccumed (instance {{ $labels.instance }})"
        description: "Table has not been vaccum for 24 hours\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: TableNotAnalyzed
      expr: time() - pg_stat_user_tables_last_autoanalyze > 60 * 60 * 24
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Table not analyzed (instance {{ $labels.instance }})"
        description: "Table has not been analyzed for 24 hours\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: TooManyConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres"}) > 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Too many connections (instance {{ $labels.instance }})"
        description: "PostgreSQL instance has too many connections\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: NotEnoughConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres"}) < 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Not enough connections (instance {{ $labels.instance }})"
        description: "PostgreSQL instance should have more connections (> 5)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        #   - alert: DeadLocks
        # expr: rate(pg_stat_database_deadlocks{pg_stat_database_de}[1m]) > 0
        # for: 5m
        #labels:
        #severity: warning
        #annotations:
        #        summary: "Dead locks (instance {{ $labels.instance }})"
        #description: "PostgreSQL has dead-locks\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: SlowQueries
      expr: avg(rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[1m])) BY (datname) > 60
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Slow queries (instance {{ $labels.instance }})"
        description: "PostgreSQL executes slow queries (> 1min)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
