version: '3.7'
services:
  node-exporter:
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --path.rootfs=/rootfs
    - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node-exporter
    image: prom/node-exporter:latest
    network_mode: host
    restart: unless-stopped
    volumes:
    - /proc:/host/proc:rw
    - /sys:/host/sys:rw
    - /:/rootfs:rw
