server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.122.90:3100/api/prom/push

scrape_configs:
  - job_name: system
    pipeline_stages:
    - docker:
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        instance: 192.168.122.90
        __path__: /var/log/*.log

  - job_name: journal
    journal:
      path: /var/log/journal
      labels:
        job: systemd-journal
        instance: 192.168.122.90
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
